version: '3'
services:
  
  mongodb:
    image: mongo:6.0.7
    restart: unless-stopped
    # command: mongod --auth --bind_ip_all --slowms=200
    command: [--auth]
    env_file: .env
    volumes: 
      - mongodb_data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - mongodb_net

  compass:
    image: mongo-express:1.0.0-alpha
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXP_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXP_PASS}
    ports:
      - ${MONGO_EXP_PORT}:8081
    depends_on:
      - mongodb
    networks:
      - mongodb_net

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    restart: unless-stopped
    volumes:
      - .:/app
      - file_upload:/app/file_upload
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - rabbitmq_go_net
      - mongodb_net
  
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    restart: unless-stopped
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
    volumes:
      - .:/app
      - file_upload:/app/file_upload
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      - rabbitmq_go_net
      - mongodb_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    restart: unless-stopped
    ports:
        - ${RABBIT_PORT}:5672
        - ${RABBIT_ADMIN_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    volumes:
        - rabbitmq_data:/rabbitmq/data/:/var/lib/rabbitmq/
        - rabbitmq_logs:/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
  mongodb_net:

volumes:
  mongodb_data:
  rabbitmq_data:
  rabbitmq_logs:
  file_upload: